# Theme
theme: 'blueboard'

# base path in php (default value is '')
php_base: 'C:/hexo/joseph/mysite'

# base path in html (default value is '')
html_base: ''

# name of your site
site_name: 'MYS'
# your name
master_name: 'MyS'
# the introduction of you
intro: 'This is mys.'
# the name of home page
home_name: 'mys home'

# your avatar's link
avatar: '".res."/avatar.png'

# other sites
othersite:
  - flag: 'goto'
    name: '去往'
    link: '/goto'
  - flag: 'blog'
    name: '博客'
    link: 'https://blog.josephz.top'
  - flag: 'relax'
    name: '休闲'
    link: 'https://mc.josephz.top'
  - flag: 'docs'
    name: '文档'
    link: 'https://doc.josephz.top'

# the birthday of your site
site_birthday: '07/21/2021'

# Units
# format:
#   - name: 
#     class: 
#     yamldir:  
#     conf:
#       - xxx: xxx
#       - yyy: yyy
units:
  - name: 'mysconfig'
    class: 'base'
    yamldir: /
    conf:
  - name: 'blueboard'
    class: theme
    yamldir:
    conf:
      - background:
        - 'https://josephz.top/res/img/pictures/wall/1.jpg'
        - 'https://josephz.top/res/img/pictures/wall/2.jpg'
        - 'https://josephz.top/res/img/pictures/wall/3.jpg'
        - 'https://josephz.top/res/img/pictures/wall/4.jpg'
  - name: 'parsedown'
    class: 'function'
    yamldir: 
    conf:
  - name: 'mbase'
    class: 'lib'
    yamldir: 
    conf:
  - name: 'aplayer'
    class: 'function'
    yamldir: 
    conf:
       - enable: true
         config: 'config.js'
  - name: 'webclock'
    class: 'function'
    yamldir: 
    conf:
  - name: 'mysnote'
    class: 'function'
    yamldir: 
    conf:
      - hpptalk: 
         - domain: ''
           theme: 'https://cdn.jsdelivr.net/gh/HexoPlusPlus/CDN@master/plugin/style/heimu.css'
  - name: 'waline'
    class: 'function'
    yamldir: 
    conf: 
      - url: 'https://blog-api-mroxoa8vg-jiaxu07.vercel.app'

# Comment System
# like waline
comment: none

head:
#  - <link rel="stylesheet" href="xxx" type="text/css"/>

include_func:

files_const:
  php_res_dir: pbase.'/res'
  html_res_dir: base.'/res'
