# Theme
theme: 'blueboard'

# base path in php (default value is '')
php_base: 'C:/hexo/joseph/mysite'

# base path in html (default value is '')
html_base: '/t/mysite'

# name of your site
site_name: 'MYS'
# your name
master_name: 'MyS'
# the introduction of you
intro: 'This is mys.'
# the name of home page
home_name: 'mys home'

# your avatar's link
avatar: '".res."/avatar.png'

othersite:
  - name: 'blog'
    link: 'https://blog.josephz.top'
  - name: 'relax'
    link: 'https://mc.josephz.top'
  - name: 'docs'
    link: 'https://doc.josephz.top'

site_birthday: '07/21/2021'

theme_color:
  light: '#95afff'
  dark: '#051f7f'

aplayer:
  enable: true
  default_cover: '".res."/img/aplayer/default.png'

# Comment System
# like waline
comment: none

head:
#  - <link rel="stylesheet" href="'.res.'/css/APlayer.min.css" type="text/css"/>

include_func:

files_const:
  php_res_dir: pbase.'/res'
  html_res_dir: base.'/res'
